# My workflow

name: My first wordkflow


on: [push, pull_request]

jobs:
  job_1:
    name: My first job
    runs-on: ${{matrix.os_version }}
    steps:
      - uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm install
      - name: Clean install dependencies and build
        run: |
          npm ci
          npm run build
        working-directory: ./temp
        shell: bash

    
