# My workflow

name: My first wordkflow


on: [push, pull_request]

jobs:
  job_1:
    name: My first job
    runs-on: ubuntu-latest
  # job_2:
  #   name: My second job
  #   needs: job_1
  # job_3:
  #   name: My third job
  #   needs: [job_1, job_2]
